/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc;

/**
 *
 * @author maria
 */
public class PanelEstadoCuenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstadoCuenta
     */
    public PanelEstadoCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        lblRetiro = new javax.swing.JLabel();
        txtRetiro = new javax.swing.JLabel();
        lblComision = new javax.swing.JLabel();
        txtComision = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblMontoFinal = new javax.swing.JLabel();
        txtMontoFinal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 210, 184));
        setMaximumSize(new java.awt.Dimension(364, 504));
        setPreferredSize(new java.awt.Dimension(364, 504));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEstado.setText("Estado de Cuenta");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNombre.setText("-");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldo.setText("Saldo actual");

        txtSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSaldo.setText("$ - - -");

        lblRetiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRetiro.setText("Retiro");

        txtRetiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRetiro.setText("$ - - -");

        lblComision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComision.setText("Comisión");

        txtComision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtComision.setText("$ - - -");

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(102, 102, 102));
        lbl10.setText("10%");

        lblMontoFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMontoFinal.setText("Monto final");

        txtMontoFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMontoFinal.setText("$ - - -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEstado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldo)
                            .addComponent(lblRetiro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblComision)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl10))
                            .addComponent(lblMontoFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMontoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txtComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblEstado)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetiro)
                    .addComponent(txtRetiro))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComision)
                    .addComponent(txtComision)
                    .addComponent(lbl10))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoFinal)
                    .addComponent(txtMontoFinal))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lblComision;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMontoFinal;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel txtComision;
    private javax.swing.JLabel txtMontoFinal;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRetiro;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables
}
