/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc;

import javax.swing.JPanel;

/**
 *
 * @author maria
 */
public class PanelRecibo extends JPanel {

    /**
     * Creates new form PanelRecibo
     */
    public PanelRecibo() {
        initComponents();
    }
    
    public void update(IModeloRetiro modelo){
        txtCuenta.setText(modelo.getRecibo().getCuenta());
        txtNombre.setText(modelo.getRecibo().getNombre());
        txtCant.setText("$"+modelo.getRecibo().getCantRetirada());
        txtComision.setText("$"+modelo.getRecibo().getComision());
        txtSaldo.setText(modelo.getSaldoUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecibo = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantRetirada = new javax.swing.JLabel();
        lblComision = new javax.swing.JLabel();
        lblSaldoActual = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtCant = new javax.swing.JLabel();
        txtComision = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        lblATM = new javax.swing.JLabel();
        lblGracias = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(364, 504));
        setPreferredSize(new java.awt.Dimension(364, 504));

        lblRecibo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRecibo.setText("Recibo");

        lblCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCuenta.setText("Cuenta");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");

        lblCantRetirada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantRetirada.setText("Cantidad retirada");

        lblComision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComision.setText("Comisión");

        lblSaldoActual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoActual.setText("Saldo actual");

        txtCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCuenta.setText("-");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombre.setText("-");

        txtCant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCant.setText("$ - - -");

        txtComision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtComision.setText("$ - - -");

        txtSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSaldo.setText("$ - - -");

        lblATM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblATM.setText("BorregoATM");

        lblGracias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGracias.setText("¡Gracias por usar!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblRecibo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCuenta)
                                    .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantRetirada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComision)
                                    .addComponent(lblSaldoActual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGracias)
                    .addComponent(lblATM))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRecibo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta)
                    .addComponent(txtCuenta))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantRetirada)
                    .addComponent(txtCant))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComision)
                    .addComponent(txtComision))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoActual)
                    .addComponent(txtSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblGracias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblATM)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblATM;
    private javax.swing.JLabel lblCantRetirada;
    private javax.swing.JLabel lblComision;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblGracias;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRecibo;
    private javax.swing.JLabel lblSaldoActual;
    private javax.swing.JLabel txtCant;
    private javax.swing.JLabel txtComision;
    private javax.swing.JLabel txtCuenta;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables
}
